### ISSUE TITLE
Unable to view profile pictures in the following page

### ISSUE THREAD

**Issue by prashantbarca** [vysakh0/railsbook#1]
http://rails-book.herokuapp.com/users
Adding a title image wouldve been another add-on i felt. :) 

![vysakh](https://f.cloud.github.com/assets/2245701/511815/3ebda160-be0f-11e2-9670-8a9cc2bdd717.jpg)

**Comment by vysakh0** [comment]
Images are broken coz i am trying to save the images in heroku, I should have put it in S3 but its not necessary. :)

**Comment by prashantbarca** [comment]
I thought Heroku gave around 200MB space? Not sufficient?

**Comment by vysakh0** [comment]
Initially the images were not broken, it looked pretty neat but generally people won't store images in Heroku, images just occupies the space too fast.
